# Generated by Django 5.0.7 on 2024-07-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="chat_model",
            field=models.CharField(
                choices=[("LLAMA3", "llama3")], default="LLAMA3", max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="theme",
            field=models.CharField(
                choices=[("DARK", "dark"), ("LIGHT", "light")],
                default="LIGHT",
                max_length=25,
            ),
        ),
    ]
