# Generated by Django 5.0.7 on 2024-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metacode", "0003_chat_edit_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="edit_content",
            field=models.TextField(),
        ),
    ]
